version = 0.1

[default]
[default.global.parameters]
stack_name = "gomimakasete-production"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
resolve_s3 = true
region = "us-east-1"
disable_rollback = false
parameter_overrides = "Environment=\"prod\" DailyBedrockBudgetUsd=5.00"
