/**
 * Calendar Sync Utility for GomiMakasete
 * Generates Google Calendar recurring template links and RFC 5545 standard .ics iCalendar files
 * with 7:30 AM morning reminder alarms (30 minutes before 8:00 AM curbside collection).
 */

export interface GarbageScheduleEvent {
  categoryKey: string;
  categoryLabel: string;
  categoryLabelJp: string;
  emoji: string;
  days: string[]; // e.g. ['Monday', 'Thursday'] or ['Wednesday']
  cutoffTime: string; // e.g. '08:00 AM'
  municipalityName: string;
  neighborhoodName: string;
}

const DAY_TO_RRULE_MAP: Record<string, string> = {
  monday: 'MO',
  tuesday: 'TU',
  wednesday: 'WE',
  thursday: 'TH',
  friday: 'FR',
  saturday: 'SA',
  sunday: 'SU',
  mon: 'MO',
  tue: 'TU',
  wed: 'WE',
  thu: 'TH',
  fri: 'FR',
  sat: 'SA',
  sun: 'SU',
  '月曜日': 'MO',
  '火曜日': 'TU',
  '水曜日': 'WE',
  '木曜日': 'TH',
  '金曜日': 'FR',
  '土曜日': 'SA',
  '日曜日': 'SU'
};

/**
 * Parses day strings into RRULE BYDAY tokens
 */
function parseDaysToRrule(days: string[] | string): string[] {
  const list = Array.isArray(days) ? days : [days];
  const rruleDays: string[] = [];

  for (const item of list) {
    const tokens = item.toLowerCase().split(/[,/&\s]+/);
    for (const t of tokens) {
      if (DAY_TO_RRULE_MAP[t] && !rruleDays.includes(DAY_TO_RRULE_MAP[t])) {
        rruleDays.push(DAY_TO_RRULE_MAP[t]);
      }
    }
  }

  return rruleDays.length > 0 ? rruleDays : ['MO'];
}

/**
 * Creates deep-link URL to open Google Calendar with pre-populated recurring event
 */
export function buildGoogleCalendarUrl(
  event: GarbageScheduleEvent
): string {
  const title = `${event.emoji} ${event.categoryLabel} (${event.categoryLabelJp}) Collection`;
  const location = `${event.neighborhoodName}, ${event.municipalityName}, Japan`;
  const details = `Japanese Municipal Waste Collection reminder.\nPlease take your trash to your neighborhood collection spot before ${event.cutoffTime}.\nEnsure correct sorting and transparent municipal bags.\n\nGenerated by GomiMakasete (ゴミ？まかせて！).`;

  // Start date: Next occurrence at 07:30 AM
  const now = new Date();
  // Format as YYYYMMDDTHHMMSS
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');

  const startIso = `${year}${month}${day}T073000`;
  const endIso = `${year}${month}${day}T080000`;

  const rruleDays = parseDaysToRrule(event.days).join(',');
  const recur = `RRULE:FREQ=WEEKLY;BYDAY=${rruleDays}`;

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: `${startIso}/${endIso}`,
    details: details,
    location: location,
    recur: recur
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Builds RFC 5545 standard .ics file string for all active neighborhood waste streams
 */
export function generateICSContent(
  municipalityName: string,
  neighborhoodName: string,
  schedules: Record<string, string[] | string>,
  cutoffTime: string = '08:00 AM'
): string {
  const timestamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//GomiMakasete//Waste Sorting Assistant//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:Garbage Schedule - ${neighborhoodName}`,
    'X-WR-TIMEZONE:Asia/Tokyo'
  ];

  const categoryConfigs: Record<string, { label: string; labelJp: string; emoji: string }> = {
    combustible: { label: 'Burnable Waste', labelJp: '燃やすごみ', emoji: '🔥' },
    plastic_packaging: { label: 'Plastics', labelJp: 'プラスチック包装', emoji: '🧴' },
    cans_bottles_pet: { label: 'Cans & PET Bottles', labelJp: '缶・ビン・PET', emoji: '🥫' },
    resources: { label: 'Paper Resources', labelJp: '資源古紙', emoji: '📦' },
    metal_ceramics_glass: { label: 'Incombustible Metal/Glass', labelJp: '不燃・陶器・ガラス', emoji: '🏺' },
    station_dropoff: { label: 'Zero Waste Station Dropoff', labelJp: 'ステーション持ち込み', emoji: '🍃' }
  };

  let eventCounter = 1;
  for (const [key, rawDays] of Object.entries(schedules)) {
    const config = categoryConfigs[key] || { label: key, labelJp: key, emoji: '🗑️' };
    const rruleDays = parseDaysToRrule(rawDays).join(',');

    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');

    lines.push(
      'BEGIN:VEVENT',
      `UID:gomi-${Date.now()}-${eventCounter}@gomimakasete.local`,
      `DTSTAMP:${timestamp}`,
      `DTSTART;TZID=Asia/Tokyo:${year}${month}${day}T073000`,
      `DTEND;TZID=Asia/Tokyo:${year}${month}${day}T080000`,
      `RRULE:FREQ=WEEKLY;BYDAY=${rruleDays}`,
      `SUMMARY:${config.emoji} ${config.label} (${config.labelJp})`,
      `DESCRIPTION:Take bags down to your neighborhood collection spot before ${cutoffTime}. Transparent bags only.`,
      `LOCATION:${neighborhoodName}, ${municipalityName}, Japan`,
      'STATUS:CONFIRMED',
      'BEGIN:VALARM',
      'TRIGGER:-PT30M',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${config.label} Collection this morning!`,
      'END:VALARM',
      'END:VEVENT'
    );
    eventCounter++;
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

/**
 * Triggers a browser download of the generated .ics file
 */
export function downloadICSFile(filename: string, content: string): void {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
