/**
 * Calendar Sync Utility for GomiMakasete
 * Generates Google Calendar recurring/one-time template links and RFC 5545 standard .ics iCalendar files
 * with 7:30 AM morning reminder alarms (30 minutes before morning curbside collection).
 */

export interface GarbageScheduleEvent {
  categoryKey: string;
  categoryLabel: string;
  categoryLabelJp: string;
  emoji: string;
  days?: string[]; // e.g. ['Monday', 'Thursday'] or ['Wednesday']
  cutoffTime: string; // e.g. '08:00 AM'
  municipalityName: string;
  neighborhoodName: string;
  targetDate?: Date; // Specific target date if single-day event
  itemsDescription?: string; // Optional list of specific scanned items to dispose
  isRecurring?: boolean; // If true, sets weekly RRULE
}

export interface DayManifestEvent {
  dayName: string;
  date: Date;
  streams: Array<{
    name: string;
    key: string;
    items: Array<{ name: string; id: string }>;
  }>;
  cutoffTime: string;
  municipalityName: string;
  neighborhoodName: string;
}

const DAY_TO_RRULE_MAP: Record<string, string> = {
  monday: 'MO',
  tuesday: 'TU',
  wednesday: 'WE',
  thursday: 'TH',
  friday: 'FR',
  saturday: 'SA',
  sunday: 'SU',
  mon: 'MO',
  tue: 'TU',
  wed: 'WE',
  thu: 'TH',
  fri: 'FR',
  sat: 'SA',
  sun: 'SU',
  '月曜日': 'MO',
  '火曜日': 'TU',
  '水曜日': 'WE',
  '木曜日': 'TH',
  '金曜日': 'FR',
  '土曜日': 'SA',
  '日曜日': 'SU'
};

const DAY_NAME_TO_INDEX: Record<string, number> = {
  sunday: 0,
  sun: 0,
  monday: 1,
  mon: 1,
  tuesday: 2,
  tue: 2,
  wednesday: 3,
  wed: 3,
  thursday: 4,
  thu: 4,
  friday: 5,
  fri: 5,
  saturday: 6,
  sat: 6
};

/**
 * Parses day strings into RRULE BYDAY tokens
 */
export function parseDaysToRrule(days: string[] | string): string[] {
  const list = Array.isArray(days) ? days : [days];
  const rruleDays: string[] = [];

  for (const item of list) {
    const tokens = item.toLowerCase().split(/[,/&\s]+/);
    for (const t of tokens) {
      if (DAY_TO_RRULE_MAP[t] && !rruleDays.includes(DAY_TO_RRULE_MAP[t])) {
        rruleDays.push(DAY_TO_RRULE_MAP[t]);
      }
    }
  }

  return rruleDays.length > 0 ? rruleDays : ['MO'];
}

/**
 * Finds the upcoming date for a given day name (e.g. "Monday" or "Mon")
 */
export function getNextDateForDayName(dayName: string): Date {
  const lower = dayName.toLowerCase();
  let targetDayIdx = -1;
  for (const [k, v] of Object.entries(DAY_NAME_TO_INDEX)) {
    if (lower.startsWith(k)) {
      targetDayIdx = v;
      break;
    }
  }

  const now = new Date();
  if (targetDayIdx === -1) {
    const tomorrow = new Date(now);
    tomorrow.setDate(tomorrow.getDate() + 1);
    return tomorrow;
  }

  const currentDay = now.getDay();
  let diff = (targetDayIdx - currentDay + 7) % 7;
  // If today is target day but morning cutoff has passed (>= 8am), target next week
  if (diff === 0 && now.getHours() >= 8) {
    diff = 7;
  } else if (diff === 0 && now.getHours() < 8) {
    diff = 0; // It's this morning!
  }

  const target = new Date(now);
  target.setDate(target.getDate() + diff);
  return target;
}

/**
 * Formats a Date object to YYYYMMDDTHHMMSS in Tokyo / local time
 */
function formatDateTime(d: Date, timeStr: '073000' | '080000'): string {
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}${month}${day}T${timeStr}`;
}

/**
 * Creates deep-link URL to open Google Calendar with pre-populated recurring or targeted single-pickup event
 */
export function buildGoogleCalendarUrl(
  event: GarbageScheduleEvent
): string {
  const title = `${event.emoji} ${event.categoryLabel} (${event.categoryLabelJp}) Waste Pickup`;
  const location = `${event.neighborhoodName}, ${event.municipalityName}, Japan`;
  
  let details = `Japanese Municipal Waste Collection reminder.\nPlease take your trash to your neighborhood collection spot before ${event.cutoffTime}.\nEnsure correct sorting and municipal designated / transparent bags.`;
  if (event.itemsDescription) {
    details += `\n\nScanned Items to Throw Out:\n${event.itemsDescription}`;
  }
  details += `\n\nGenerated by GomiMakasete (ゴミ？まかせて！).`;

  // Determine starting date
  let eventDate = event.targetDate;
  if (!eventDate && event.days && event.days.length > 0) {
    eventDate = getNextDateForDayName(event.days[0]);
  }
  if (!eventDate) {
    eventDate = new Date();
    eventDate.setDate(eventDate.getDate() + 1);
  }

  const startIso = formatDateTime(eventDate, '073000');
  const endIso = formatDateTime(eventDate, '080000');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: `${startIso}/${endIso}`,
    details: details,
    location: location
  });

  // If recurring requested and days available, add RRULE
  if (event.isRecurring && event.days && event.days.length > 0) {
    const rruleDays = parseDaysToRrule(event.days).join(',');
    params.set('recur', `RRULE:FREQ=WEEKLY;BYDAY=${rruleDays}`);
  }

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Creates deep-link URL for an entire day's scanned manifest (only days that actually have items!)
 */
export function buildDayManifestGoogleCalendarUrl(
  manifest: DayManifestEvent
): string {
  const streamNames = manifest.streams.map(s => s.name).join(', ');
  const title = `🗑️ Waste Pickup: ${streamNames}`;
  const location = `${manifest.neighborhoodName}, ${manifest.municipalityName}, Japan`;

  const itemLines: string[] = [];
  manifest.streams.forEach(s => {
    const names = s.items.map(i => `• ${i.name}`).join('\n');
    itemLines.push(`[${s.name}]:\n${names}`);
  });

  const details = `Japanese Municipal Waste Collection Reminder for ${manifest.dayName}.\n\nItems to put out before ${manifest.cutoffTime}:\n${itemLines.join('\n\n')}\n\nStation rules: Place bags at neighborhood dropoff point. Use correct transparent or translucent bags.\n\nGenerated by GomiMakasete (ゴミ？まかせて！).`;

  const startIso = formatDateTime(manifest.date, '073000');
  const endIso = formatDateTime(manifest.date, '080000');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: `${startIso}/${endIso}`,
    details: details,
    location: location
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

/**
 * Builds RFC 5545 standard .ics file string for all active neighborhood waste streams
 * Option for full monthly/recurring schedule or strictly days with scanned items.
 */
export function generateICSContent(
  municipalityName: string,
  neighborhoodName: string,
  schedules: Record<string, string[] | string>,
  cutoffTime: string = '08:00 AM',
  itemSpecificDays?: Array<{
    dayName: string;
    date: Date;
    streams: Array<{ name: string; items: Array<{ name: string }> }>;
  }>
): string {
  const timestamp = new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//GomiMakasete//Waste Sorting Assistant//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:Garbage Schedule - ${neighborhoodName}`,
    'X-WR-TIMEZONE:Asia/Tokyo'
  ];

  // If specific item days are provided and requested, only output targeted events for those items
  if (itemSpecificDays && itemSpecificDays.length > 0) {
    let eventCounter = 1;
    for (const d of itemSpecificDays) {
      const year = d.date.getFullYear();
      const month = String(d.date.getMonth() + 1).padStart(2, '0');
      const day = String(d.date.getDate()).padStart(2, '0');

      const streamSummaries = d.streams.map(s => s.name).join(' & ');
      const itemDesc = d.streams.map(s => `${s.name}: ${s.items.map(i => i.name).join(', ')}`).join('\\n');

      lines.push(
        'BEGIN:VEVENT',
        `UID:gomi-item-${Date.now()}-${eventCounter}@gomimakasete.local`,
        `DTSTAMP:${timestamp}`,
        `DTSTART;TZID=Asia/Tokyo:${year}${month}${day}T073000`,
        `DTEND;TZID=Asia/Tokyo:${year}${month}${day}T080000`,
        `SUMMARY:🗑️ Waste Throw-out: ${streamSummaries}`,
        `DESCRIPTION:Items to take down before ${cutoffTime}:\\n${itemDesc}\\n\\nGenerated by GomiMakasete.`,
        `LOCATION:${neighborhoodName}, ${municipalityName}, Japan`,
        'STATUS:CONFIRMED',
        'BEGIN:VALARM',
        'TRIGGER:-PT30M',
        'ACTION:DISPLAY',
        `DESCRIPTION:Reminder: Put out ${streamSummaries} this morning!`,
        'END:VALARM',
        'END:VEVENT'
      );
      eventCounter++;
    }
    lines.push('END:VCALENDAR');
    return lines.join('\r\n');
  }

  // Otherwise, full month recurring schedule for the entire neighborhood
  const categoryConfigs: Record<string, { label: string; labelJp: string; emoji: string }> = {
    combustible: { label: 'Burnable Waste', labelJp: '燃やすごみ', emoji: '🔥' },
    plastic_packaging: { label: 'Plastics', labelJp: 'プラスチック包装', emoji: '🧴' },
    cans_bottles_pet: { label: 'Cans & PET Bottles', labelJp: '缶・ビン・PET', emoji: '🥫' },
    resources: { label: 'Paper Resources', labelJp: '資源古紙', emoji: '📦' },
    metal_ceramics_glass: { label: 'Incombustible Metal/Glass', labelJp: '不燃・陶器・ガラス', emoji: '🏺' },
    station_dropoff: { label: 'Zero Waste Station Dropoff', labelJp: 'ステーション持ち込み', emoji: '🍃' }
  };

  let eventCounter = 1;
  for (const [key, rawDays] of Object.entries(schedules)) {
    const config = categoryConfigs[key] || { label: key, labelJp: key, emoji: '🗑️' };
    const rruleDays = parseDaysToRrule(rawDays).join(',');

    // Start on the first occurrence of this weekday
    const firstDay = Array.isArray(rawDays) ? rawDays[0] : rawDays;
    const nextOccur = getNextDateForDayName(firstDay);

    const year = nextOccur.getFullYear();
    const month = String(nextOccur.getMonth() + 1).padStart(2, '0');
    const day = String(nextOccur.getDate()).padStart(2, '0');

    lines.push(
      'BEGIN:VEVENT',
      `UID:gomi-${Date.now()}-${eventCounter}@gomimakasete.local`,
      `DTSTAMP:${timestamp}`,
      `DTSTART;TZID=Asia/Tokyo:${year}${month}${day}T073000`,
      `DTEND;TZID=Asia/Tokyo:${year}${month}${day}T080000`,
      `RRULE:FREQ=WEEKLY;BYDAY=${rruleDays}`,
      `SUMMARY:${config.emoji} ${config.label} (${config.labelJp})`,
      `DESCRIPTION:Take bags down to your neighborhood collection spot before ${cutoffTime}. Transparent bags only.`,
      `LOCATION:${neighborhoodName}, ${municipalityName}, Japan`,
      'STATUS:CONFIRMED',
      'BEGIN:VALARM',
      'TRIGGER:-PT30M',
      'ACTION:DISPLAY',
      `DESCRIPTION:Reminder: ${config.label} Collection this morning!`,
      'END:VALARM',
      'END:VEVENT'
    );
    eventCounter++;
  }

  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}

/**
 * Triggers a browser download of the generated .ics file
 */
export function downloadICSFile(filename: string, content: string): void {
  if (typeof window === 'undefined') return;
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
